// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Sidebar para About Me
  aboutMeSidebar: [
    {
      type: 'autogenerated',
      dirName: 'about-me', // pega todos os arquivos da pasta about-me
    },
  ],
  // Sidebar para Docs Example
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'docs-example', // pega todos os arquivos da pasta docs-example
    },
  ],
};

export default sidebars;
